version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/sample"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/test"
    schedule:
      interval: "weekly"
