logFilters:
  - code: YN0076
    level: discard

nodeLinker: node-modules

plugins:
  - checksum: e3ca535b4c4288976eebb726082e2e6547c43e0ba1492b3ddbb0cdadc9d61d82ff14307358da06c46a446328345a464364d6c148b2d39fccc18cf6d232291858
    path: .yarn/plugins/@yarnpkg/plugin-nolyfill.cjs
    spec: 'https://raw.githubusercontent.com/wojtekmaj/yarn-plugin-nolyfill/v0.1.1/bundles/@yarnpkg/plugin-nolyfill.js'
