compressionLevel: mixed

logFilters:
  - code: YN0076
    level: discard

nodeLinker: node-modules

plugins:
  - checksum: 04cbf7ea36b0aaedbec723f6f5165e80f817e1ef242a9d811ebca7977ec6b8756811d9406a0ccd2968f9e9768b426b2213a736aa2c6252f2c5631f6d4de2162b
    path: .yarn/plugins/@yarnpkg/plugin-nolyfill.cjs
    spec: 'https://raw.githubusercontent.com/wojtekmaj/yarn-plugin-nolyfill/v0.1.0/bundles/@yarnpkg/plugin-nolyfill.js'
